Add job to check results so we don't need to add matrix of builds to branch protections

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -95,3 +95,14 @@ jobs:
         with:
           name: NuGet package
           path: ./nuget.package/*.nupkg
+  ci:
+    name: ci
+    needs: [build, package]
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Check results
+        run: |
+          if [ "${{ needs.build.result }}" != "success" ] || [ "${{ needs.package.result }}" != "success" ]; then
+            echo "One or more jobs failed"
+            exit 1
+          fi
